package de.idealo.projectoverviewhackday.base

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(RepositoryServiceProperties::class)
class RepositoryServiceConfiguration
