spring:
  main:
    banner-mode: off

services:
  repository:
    project: ~
    excluded-repositories: []

adapters:
  bit-bucket:
    url: ~
    token: ~
  gitea:
    url: ~
    token: ~

feign:
  okhttp:
    enabled: true

security:
  allowed-origins: ~
