spring:
  main:
    banner-mode: off
  cache:
    type: simple

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

projectoverview:
  repository:
    dir: ./repositories
  security:
    allowed-origins: ~
  maven:
    temp-dir: ./maven-temp
    executable: ~

---
spring:
  profiles: dev

projectoverview:
  security:
    allowed-origins: http://localhost:3000
