spring:
  main:
    banner-mode: off

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

services:
  repository:
    project: ~
    dir: ~

adapters:
  bit-bucket:
    url: ~
    token: ~
  gitea:
    url: ~
    token: ~

security:
  allowed-origins: ~
