spring:
  main:
    banner-mode: off

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

projectoverview:
  repository:
    dir: ./repositories
  security:
    allowed-origins: ~
