package de.idealo.projectoverviewhackday.modules.repository.service

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(RepositoryServiceProperties::class)
class RepositoryServiceConfiguration
