package de.idealo.projectoverviewhackday.maven

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(MavenModelResolverProperties::class)
class MavenModelResolverConfiguration
